name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Squeeze
      uses: ./.github/action/debiansqueeze
      id: debiansqueeze
    - name: Compile devkitARM on Debian Buster
      uses: ./.github/action/debianbuster
      id: debianbuster
    - name: Compile devkitARM on Ubuntu 19.10 Eoan
      uses: ./.github/action/ubuntueoan
      id: ubuntueoan
    - name: Upload from Debian Squeeze
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-squeeze.tar.gz
        path: devkitARM-r32-linux_debian-squeeze.tar.gz
    - name: Upload from Debian Buster
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-buster.tar.gz
        path: devkitARM-r32-linux_debian-buster.tar.gz
    - name: Upload from Ubuntu 19.10 Eoan
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-eoan.tar.gz
        path: devkitARM-r32-linux_ubuntu-eoan.tar.gz

