name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM
      uses: ./.github/actions
      id: asdf
    - name: Upload Debian Buster
      uses: actions/upload-artifact@v1
      with: 
        name: devkitARM-r32-linux_debian-buster.tar.gz
        path: devkitARM-r32-linux_debian-buster.tar.gz
    - name: Upload Debian Squeeze
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-squeeze.tar.gz
        path: devkitARM-r32-linux_debian-squeeze.tar.gz

