name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: Leseratte10/test@faa9e4ea2afe883d8ff6cb87d9d5eeaea132603e
      id: asdf
    - uses: actions/upload-artifact@v1
      with: 
        name: devkitARM-r32-linux.tar.gz
        path: devkitARM-r32-linux.tar.gz
