name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: Leseratte10/compile-devkitARM-r32@5bc6389ce8e6ea34b459b7b6fa6110f09ac19b8c
      id: asdf
    - uses: actions/upload-artifact@v1
      with: 
        name: devkitARM-r32-linux.tar.gz
        path: devkitARM-r32-linux.tar.gz
