name: CI

on: [push]

jobs:
  debian-squeeze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Squeeze
      uses: ./.github/action/debiansqueeze
      id: debiansqueeze
    - name: Upload from Debian Squeeze
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-squeeze.tar.gz
        path: devkitARM-r32-linux_debian-squeeze.tar.gz
        
  debian-wheezy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Wheezy
      uses: ./.github/action/debianwheezy
      id: debianwheezy
    - name: Upload from Debian Wheezy
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-wheezy.tar.gz
        path: devkitARM-r32-linux_debian-wheezy.tar.gz
        
  debian-jessie:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Jessie
      uses: ./.github/action/debianjessie
      id: debianjessie
    - name: Upload from Debian Jessie
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-jessie.tar.gz
        path: devkitARM-r32-linux_debian-jessie.tar.gz
        
  debian-stretch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Stretch
      uses: ./.github/action/debianstretch
      id: debianstretch
    - name: Upload from Debian Stretch
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-stretch.tar.gz
        path: devkitARM-r32-linux_debian-stretch.tar.gz

  debian-buster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Buster
      uses: ./.github/action/debianbuster
      id: debianbuster
    - name: Upload from Debian Buster
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-buster.tar.gz
        path: devkitARM-r32-linux_debian-buster.tar.gz

  debian-bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Debian Bullseye
      uses: ./.github/action/debianbullseye
      id: debianbullseye
    - name: Upload from Debian Bullseye
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_debian-bullseye.tar.gz
        path: devkitARM-r32-linux_debian-bullseye.tar.gz

  ubuntu-xenial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 16.04 Xenial LTS
      uses: ./.github/action/ubuntuxenial
      id: ubuntuxenial
    - name: Upload from Ubuntu 16.04 Xenial LTS
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-xenial.tar.gz
        path: devkitARM-r32-linux_ubuntu-xenial.tar.gz

  ubuntu-bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 18.04 Bionic LTS
      uses: ./.github/action/ubuntubionic
      id: ubuntubionic
    - name: Upload from Ubuntu 18.04 Bionic LTS
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-bionic.tar.gz
        path: devkitARM-r32-linux_ubuntu-bionic.tar.gz

  ubuntu-focal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 20.04 Focal
      uses: ./.github/action/ubuntufocal
      id: ubuntufocal
    - name: Upload from Ubuntu 20.04 Focal
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-focal.tar.gz
        path: devkitARM-r32-linux_ubuntu-focal.tar.gz

  ubuntu-hirsute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 21.04 Hirsute
      uses: ./.github/action/ubuntuhirsute
      id: ubuntuhirsute
    - name: Upload from Ubuntu 21.04 Hirsute
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-hirsute.tar.gz
        path: devkitARM-r32-linux_ubuntu-hirsute.tar.gz

  ubuntu-impish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 21.10 Impish
      uses: ./.github/action/ubuntuimpish
      id: ubuntuimpish
    - name: Upload from Ubuntu 21.10 Impish
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-impish.tar.gz
        path: devkitARM-r32-linux_ubuntu-impish.tar.gz
        
  ubuntu-jammy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile devkitARM on Ubuntu 22.04 Jammy
      uses: ./.github/action/ubuntuimpish
      id: ubuntujammy
    - name: Upload from Ubuntu 22.04 Jammy
      uses: actions/upload-artifact@v1
      with:
        name: devkitARM-r32-linux_ubuntu-jammy.tar.gz
        path: devkitARM-r32-linux_ubuntu-jammy.tar.gz
        